

source "https://rubygems.org"

gem "net-smtp", "~> 0.5.1"
gem "pony",     "~> 1.13"
gem "puma",     "~> 7.1"
gem "sinatra",  "~> 4.2"
gem "rackup",   "~> 2.2"

gem "solarwinds_apm"

gem "google-protobuf", "~> 4.33.0"

gem "ostruct"

gem "openfeature-sdk", "~> 0.4"
gem "openfeature-flagd-provider", "~> 0.1"
